### ISSUE TITLE
Weather not updated.

### ISSUE THREAD

**Issue by deam0n** [Belgingur/WOD-Documentation#1]
![image](https://user-images.githubusercontent.com/1869650/95559385-f1ab6800-0a17-11eb-8aab-40b8318a6a1d.png)

**Comment by logi** [comment]
This particular forecast is no longer being run since there was no funding for the resources it was consuming.
```
     ref      | upstream_name | analyses |         triggered          |        expires         
--------------+---------------+----------+----------------------------+------------------------
 nweurope-5-1 | global-gfs    | {12}     | {"2019-06-26 12:00:00+00"} | 2019-06-27 00:00:00+00
```
~Where did you even find it?~ @olafurrognvaldsson had commented it out from https://europe.belgingur.is/ by the time I looked.
